### ISSUE TITLE
Rendering Problem on Nuxt3 

### ISSUE THREAD

**Issue by Ismailsnbs** [egidiusmengelberg/nuxt-aos#18] opened 2024-01-31 10:41 UTC
it will only show the animation on the first visit on every page (or again after a refresh), but when navigating to a page more than once it seems to remember that it already did the animation and is not doing the animation again. i did data-aos-once="false" but nothing changed.
in implemention of aos i follow the https://nuxt.com/modules/aos guide but, it didnt work then ı make this;
<script setup lang="ts">

import AOS from 'aos';
onMounted(() => AOS.init());

</script>

<template>
   <div data-aos="fade-left" data-aos-duration="1000"></div>
</template>
and it worked but now, it render once

**Comment by egidiusmengelberg** [comment] 2024-01-31 12:41
```js
<script setup lang="ts"> import AOS from 'aos'; onMounted(() => AOS.init()); </script>
```

should not be necessary. Are there any errors in your browser console? What version of nuxt are you using?

**Comment by egidiusmengelberg** [comment] 2024-02-26 11:35
Does this still happen in the newer versions of this package?

**Comment by Gunther-443** [comment] 2024-02-27 15:50
For information (not a bug) you must build. It doesn't work un dev mode

**Comment by Ismailsnbs** [comment] 2024-03-01 11:56
> Does this still happen in the newer versions of this package?

all good right now

**Comment by egidiusmengelberg** [comment] 2024-03-04 18:52
great! closing this issue

**Closed as completed by egidiusmengelberg** 2024-03-04 18:52 UTC
