### ISSUE TITLE
Uncaught SyntaxError import debounce from "/_nuxt/node_modules/.pnpm/lodash.debounce@4.0.8/node_modules/lodash.debounce/index.js?v=ec69d98d";

### ISSUE THREAD

**Issue by Kaysem** [egidiusmengelberg/nuxt-aos#6] opened 2023-09-14 09:13 UTC
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/lodash.debounce@4.0.8/node_modules/lodash.debounce/index.js?v=ec69d98d' does not provide an export named 'default' (at aos.esm.js?v=ec69d98d:2:8)

**Comment by egidiusmengelberg** [comment] 2023-09-15 07:20
Yeah i'm aware of the issue. Seems to be a problem with cjs and esm imports. I'm very busy at the moment so can't investigate and fix the issue at this time. But feel free to create a PR.

**Comment by tolgahanbeyazoglu** [comment] 2023-09-28 10:35
@Kaysem Did you solve the problem?

**Comment by YourItalianChef** [comment] 2023-10-05 09:48
@tolgahanbeyazoglu you can just add AOS like plugins
download aos.

named file like:
aos.cliente.js 

inside file
import AOS from 'aos'
import 'aos/dist/aos.css'


export default defineNuxtPlugin(nuxtApp => {
  console.log(nuxtApp)
  if (typeof window !== 'undefined') {
    nuxtApp.AOS = AOS.init()
  }
})

**Comment by egidiusmengelberg** [comment] 2023-10-28 10:43
There is a PR ready to be merged at the AOS library, [link](https://github.com/michalsnik/aos/pull/423). But it seems the project is dead. Last update was 5 years ago. I'll try and email the author next week. If that doesn't work I could create a fork and update it myself. But that would not be a elegant solution. Anybody any ideas?

**Comment by rubynouille** [comment] 2023-10-28 11:27
We could maintain it yeah, I'd be down to contribute if you fork and update
EDIT: Unrelated but could you update the npm package please? 
EDIT 2: Oop okay this one's on me for npm, sorry, fixed in #9

**Comment by khalednadam** [comment] 2023-11-09 19:54
Hello, is there any work around for this issue

**Comment by egidiusmengelberg** [comment] 2023-11-09 20:02
I think writing your own nuxt3 plugin would work. https://stackoverflow.com/questions/71484930/using-aos-with-nuxt3

**Comment by Islam8Bahaa** [comment] 2023-12-17 12:12
You can try this [nuxt3-aos](https://www.npmjs.com/package/nuxt3-aos) it working Good

**Comment by tolgahanbeyazoglu** [comment] 2024-01-02 12:25
@Islam8Bahaa  Yes, it works smoothly thanks to the module you specified.

**Comment by BayBreezy** [comment] 2024-01-11 05:13
The issue is actually because the aos package needs to be transpiled. It should also be added to the list of optimizedDeps. I will do a PR soon.

**Comment by tolgahanbeyazoglu** [comment] 2024-01-11 13:10
@BayBreezy  We are waiting

**Comment by BayBreezy** [comment] 2024-01-11 13:27
I did the PR lol. My bad for not mentioning it here. Its PR #12 @tolgahanbeyazoglu

**Comment by egidiusmengelberg** [comment] 2024-01-11 18:29
Yeah nice, in v1.2.2 it seems fixed. Just tried it with a fresh nuxt project (v3.9.0) so closing this issue.

**Closed as completed by egidiusmengelberg** 2024-01-11 18:29 UTC
